name: CI
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
env:
  IMAGE_TAG: latest
jobs:
  validate:
    name: Validate Bicep
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/arm-deploy@v1
      name: Run preflight validation
      with:
        resourceGroupName: ${{ env.RESOURCE_GROUP }}
        template: ./deploy/azure-container-apps.bicep
        deploymentMode: Validate
        parameters: 'tenantId=${{ secrets.AZURE_TENANT_ID }} appId=${{ secrets.AZURE_APP_ID }} appSecret=${{ secrets.AZURE_APP_SECRET }}'
  bicep:
    name: Build Docker Image
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/tomkerkhove/api-management-chaos-monkey-api
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./src/ --file ./src/ChaosMonkey.API/Dockerfile --tag ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}